"""Start database

Revision ID: 2033f52cf6be
Revises:
Create Date: 2025-03-01 19:04:09.042335

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2033f52cf6be"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tickets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("show", sa.String(), nullable=True),
        sa.Column("user", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tickets")
    # ### end Alembic commands ###
