"""Add ticket details one to one

Revision ID: 5afd83cfc7fd
Revises: ee977cc710a1
Create Date: 2025-03-01 19:46:47.696292

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5afd83cfc7fd"
down_revision = "ee977cc710a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket_details",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("seat", sa.String(), nullable=True),
        sa.Column("ticket_type", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket_details")
    # ### end Alembic commands ###
