"""Create events and many to one

Revision ID: ae2c96f0314c
Revises: 5afd83cfc7fd
Create Date: 2025-03-01 19:48:21.583499

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ae2c96f0314c"
down_revision = "5afd83cfc7fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tickets") as batch_op:
        batch_op.add_column(sa.Column("event_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_tickets_event_id_events",
            "events",
            ["event_id"],
            ["id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tickets") as batch_op:
        batch_op.drop_constraint(
            "fk_tickets_event_id_events",
            type_="foreignkey",
        )
        batch_op.drop_column("event_id")
    op.drop_table("events")
    # ### end Alembic commands ###
